<a href="https://colab.research.google.com/github/ntnkiev/goit-ds-hw-04/blob/main/goit_ds_hw04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9 ,10], dtype=float)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
m = np.zeros((3, 3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
rand55 = np.random.random((5, 5))*10//1
print(rand55)

[[2. 3. 9. 3. 6.]
 [2. 2. 8. 0. 5.]
 [5. 9. 0. 6. 4.]
 [1. 2. 8. 9. 4.]
 [5. 1. 5. 8. 2.]]


Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
rand44 = np.random.random((4, 4))
print(rand44)

[[0.57276351 0.7010899  0.85960352 0.00603897]
 [0.23261796 0.48025127 0.91933783 0.70550749]
 [0.36850743 0.83632504 0.30502071 0.853596  ]
 [0.42383719 0.84189373 0.02768072 0.14430652]]


Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
a = np.random.random(5)*10//1
b = np.random.random(5)*10//1
print(a, b)
print(a+b)
print(a-b)
print(a*b)

[3. 6. 2. 5. 3.] [9. 9. 9. 6. 4.]
[12. 15. 11. 11.  7.]
[-6. -3. -7. -1. -1.]
[27. 54. 18. 30. 12.]


Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
a = np.random.random(7)*10//1
b = np.random.random(7)*10//1
print(a)
print(b)
print(np.dot(a, b))

[4. 3. 0. 6. 0. 1. 9.]
[3. 8. 2. 8. 7. 5. 6.]
143.0


Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
a = np.random.random((2, 2))*10//1
b = np.random.random((2, 3))*10//1
print(a)
print(b)
print(np.dot(a, b))

[[3. 5.]
 [4. 2.]]
[[9. 7. 9.]
 [0. 3. 3.]]
[[27. 36. 42.]
 [36. 34. 42.]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
rand33 = np.random.random((3, 3))*10//1
print(rand33)
print(np.linalg.inv(rand33))

[[1. 8. 1.]
 [1. 7. 2.]
 [2. 6. 2.]]
[[ 0.2 -1.   0.9]
 [ 0.2  0.  -0.1]
 [-0.8  1.  -0.1]]
