<a href="https://colab.research.google.com/github/ntnkiev/goit-ds-hw-04/blob/main/goit_ds_hw04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9 ,10], dtype=float)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [41]:
m33 = np.zeros((3, 3), dtype=int)
print(m33)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [42]:
m55 = np.random.randint(1, 11, (5, 5))
print(m55)

[[ 8  6  7  9  7]
 [ 5  1  2  1  5]
 [ 9  5  2  8  5]
 [ 5  8  9  4  7]
 [10  4  5  7  1]]


Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [43]:
m44 = np.random.random((4, 4))
print(m44)

[[0.2630981  0.41610128 0.85235563 0.76261329]
 [0.19072846 0.73939911 0.77524352 0.16699105]
 [0.01871776 0.50545539 0.04423672 0.39906153]
 [0.10308602 0.72577957 0.57682572 0.65286674]]


Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [44]:
m1 = np.random.randint(1, 11, (5))
m2 = np.random.randint(1, 11, (5))
print(m1, m2)
print(m1 + m2)
print(m1 - m2)
print(m1 * m2)

[ 9 10  9  5  2] [5 3 8 5 9]
[14 13 17 10 11]
[ 4  7  1  0 -7]
[45 30 72 25 18]


Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [16]:
a = np.random.random(7)
b = np.random.random(7)
print(a)
print(b)
print(np.dot(a, b))

[0.17456077 0.58220767 0.70769727 0.858013   0.87477224 0.90080058
 0.30445237]
[0.23285148 0.24538876 0.61582015 0.5611242  0.55858774 0.53244922
 0.5060509 ]
2.223116061230587


Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [45]:
m22 = np.random.randint(1, 11, (2, 2))
m23 = np.random.randint(1, 11, (2, 3))
print(m22)
print(m23)
print(np.dot(m22, m23))

[[9 8]
 [7 3]]
[[1 7 2]
 [3 2 8]]
[[33 79 82]
 [16 55 38]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [46]:
m33 = np.random.randint(1, 11, (3, 3))
print(m33)
print(np.linalg.inv(m33))

[[ 5  8  1]
 [ 3  1  9]
 [10 10  3]]
[[-0.37339056 -0.06008584  0.30472103]
 [ 0.34763948  0.02145923 -0.18025751]
 [ 0.08583691  0.12875536 -0.08154506]]


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [47]:
m44 = np.random.random((4, 4))
print(m44)
m44tr = m44.T
print(m44tr)

[[0.46328463 0.51976403 0.27989416 0.87887518]
 [0.05783446 0.03441837 0.69844073 0.0247188 ]
 [0.54016962 0.72883162 0.31289432 0.02693794]
 [0.04538711 0.17579383 0.49180483 0.70824553]]
[[0.46328463 0.05783446 0.54016962 0.04538711]
 [0.51976403 0.03441837 0.72883162 0.17579383]
 [0.27989416 0.69844073 0.31289432 0.49180483]
 [0.87887518 0.0247188  0.02693794 0.70824553]]


Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [48]:
m34 = np.random.randint(1, 11, (3, 4))
v = np.random.randint(1, 11, (4))
print(m34)
print(v)
print(np.dot(m34, v))

[[ 9  7 10  2]
 [ 2  9  3  6]
 [ 6  5  4  2]]
[6 8 4 2]
[154 108  96]


Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [20]:
m23 = np.random.random((2, 3))
v = np.random.random((3))
print(m23)
print(v)
print(np.dot(m23, v))

[[0.04577708 0.73454836 0.89945709]
 [0.45543309 0.21229124 0.82724346]]
[0.18704644 0.75917646 0.68382097]
[1.18128189 0.81204008]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [21]:
m1 = np.random.randint(1, 11, (2, 2))
m2 = np.random.randint(1, 11, (2, 2))
print(m1)
print(m2)
print(m1 * m2)

[[ 4 10]
 [10  3]]
[[ 6  4]
 [ 5 10]]
[[24 40]
 [50 30]]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [24]:
m1 = np.random.randint(1, 11, (2, 2))
m2 = np.random.randint(1, 11, (2, 2))
print(m1)
print(m2)
print(np.dot(m1, m2))

[[1 4]
 [4 2]]
[[ 8  5]
 [10  3]]
[[48 17]
 [52 26]]


Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [25]:
m55 = np.random.randint(1, 101, (5, 5))
print(m55)
print(m55.sum())

[[18 71 72 36 69]
 [31 43 82  8 90]
 [39 59 84 38 76]
 [70 25 45 55 98]
 [ 2 37 26  1 86]]
1261


Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [26]:
m1 = np.random.randint(1, 11, (4, 4))
m2 = np.random.randint(1, 11, (4, 4))
print(m1)
print(m2)
print(m1 - m2)

[[8 4 5 2]
 [9 2 7 3]
 [9 1 6 8]
 [6 2 8 9]]
[[ 1  6  8  6]
 [ 7  7  8 10]
 [ 3  7  3  1]
 [ 5  7  8  9]]
[[ 7 -2 -3 -4]
 [ 2 -5 -1 -7]
 [ 6 -6  3  7]
 [ 1 -5  0  0]]


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [30]:
m33 = np.random.random((3, 3))
print(m33)
v = [m33[i].sum() for i in range(len(m33))]
print(v)

[[0.35448119 0.7471389  0.66989308]
 [0.51175276 0.03417271 0.45292538]
 [0.60025192 0.11835657 0.73617335]]
[1.7715131691067887, 0.9988508514949872, 1.4547818313448309]


Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [38]:
m34 = np.random.randint(0, 100, (3, 4))
print(m34)
print(m34 * m34)

[[36 23 66  1]
 [46 54 12 79]
 [83 46 15 60]]
[[1296  529 4356    1]
 [2116 2916  144 6241]
 [6889 2116  225 3600]]


Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [40]:
v = np.random.randint(1, 51, (4))
print(v)
v_sqrt = np.sqrt(v)
print(v_sqrt)

[46 23 49 20]
[6.78232998 4.79583152 7.         4.47213595]
